### PR TITLE
Now the whole app does not blow up

### LINKED ISSUE #229: Fix introducing wrong provider breaking whole app

### PR DESCRIPTION
**Pull request by mocomacode**
Closes #229

### CODE REVIEW

File: restapi/SOLID/API.ts [hunk 1]
```diff
@@ -74,16 +74,17 @@ export class SolidConnection {
 		//Log in to the session, wait for redirect,
 		//and return the promise.
 		if(!this.isLoggedIn()) 
-			await this._session.login({
-				redirectUrl: redirect,
-				oidcIssuer: this._identityProvider,
-				clientName: this.SOLID_CLIENT_NAME,
-				handleRedirect: (url) => res.redirect(url)
-			});
+		await this._session.login({
```
Comment (nic9las) [inline restapi/SOLID/API.ts:77]: INDENTATIONINDENTATION

**Review by nic9las — CHANGES_REQUESTED** [review]
INDENTATION

TE FALTA UNA INDENTATION

**Review by nic9las — APPROVED** [review]
